# Generated by Django 5.2.8 on 2025-12-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount_percentage',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(db_index=True, default='PS4/PS5', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='psn_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamepricehistory',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-discount_percentage'], name='games_game_discoun_21d02b_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['platform', 'genre'], name='games_game_platfor_913022_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-last_update'], name='games_game_last_up_303414_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepricehistory',
            index=models.Index(fields=['game', '-date'], name='games_gamep_game_id_e5d523_idx'),
        ),
    ]
